lion5/component-library

.storybook/preview.js, src/atoms/app-bars/NavBar/NavBar.stories.ts, src/atoms/app-bars/NavBar/NavBar.vue, src/atoms/app-bars/NavBar/navItem.ts, src/atoms/modals/LocationPermissionModal/LocationPermissionModal.vue
- Generalize Navbar
- Add VueRouter to storybook
Fixes #58
=> Feat: Generalize Nav Bar

src/atoms/boxes/Boxes.mdx, src/atoms/buttons/Buttons.mdx, src/atoms/cards/Cards.mdx
Adds `mdx` written docs to boxes, buttons and cards directories to display the components in a short overview
=> Add Summary Docs to Boxes, Buttons and Cards

.storybook/main.ts, package-lock.json, package.json
At this moment, we cannot document our css custom props. This addon would allow us to document them too.
=> Add CSS Custom Props Addon

packages/firebase/package.json, packages/gridstack/package.json, packages/leaflet/package.json
=> fix(leaflet,gridstack,firebase): :bug: add missing style exports

package-lock.json, packages/gridstack/src/components/SaveDashboardModal/SaveDashboardModal.vue
Small style fixes in dashboard
=> Fix dashboard style

packages/firebase/src/composables/useFirebaseStorage.ts, packages/gridstack/src/components/SaveDashboardModal/SaveDashboardModal.vue
=> fix: dashboard style 2

package-lock.json, packages/firebase/package.json
Hopefully this fixes the bug in digi map
=> fix(firebase): :arrow_down: change firebase version to 9.22.0

packages/core/src/components/inputs/BaseInputWrapper/BaseInputWrapper.spec.ts, packages/core/src/components/inputs/BaseInputWrapper/BaseInputWrapper.vue, packages/core/src/components/inputs/CodeInput/CodeInput.spec.ts, packages/core/src/components/inputs/CodeInput/CodeInput.stories.ts, packages/core/src/components/inputs/CodeInput/CodeInput.vue, packages/core/src/components/inputs/CodeInput/CodePartTextInput.spec.ts, packages/core/src/components/inputs/CodeInput/CodePartTextInput.vue, packages/core/src/components/inputs/CodeInput/codeInputValidation.ts
=> add CodeInput

packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.stories.ts, packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.vue, packages/gridstack/src/components/DashboardBar/DashboardBar.vue, packages/gridstack/src/components/DeleteDashboardModal/DeleteDashboardModal.vue, packages/gridstack/src/components/EditButton/EditButton.spec.ts, packages/gridstack/src/components/EditButton/EditButton.vue, packages/gridstack/src/components/SaveDashboardModal/SaveDashboardModal.vue
Add a delete functionality to Configurable Dashboard to delete persisted dashboard configurations.
=> add: Delete button to dashboard

packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.vue, packages/gridstack/src/components/DeleteDashboardModal/DeleteDashboardModal.vue, packages/gridstack/src/components/SaveDashboardModal/SaveDashboardModal.vue
Additional fix on close modal on save and delete
=> [Fix] Dashboard modal close on confirm save 2 - keep edit mode on and pass proper configuration name to delete modal

packages/core/src/components/modals/ApprovalModal/ApprovalModal.vue
Adding v-bind attributes to ApprovalModal.vue
=> Bug: Not able to add attributes to ApprovalModal

packages/core/src/components/inputs/BaseInput/BaseInput.vue, packages/core/src/components/inputs/BaseInputV2/BaseInputV2.spec.ts, packages/core/src/components/inputs/BaseInputV2/BaseInputV2.vue, packages/core/src/components/inputs/BaseInputV3/BaseInputV3.spec.ts, packages/core/src/components/inputs/BaseInputV3/BaseInputV3.stories.ts, packages/core/src/components/inputs/BaseInputV3/BaseInputV3.vue, packages/core/src/components/inputs/BaseInputWrapper/BaseInputWrapper.vue, packages/firebase/.storybook/main.scss, packages/gridstack/src/components/ConfigurableDashboard/ConfigurableDashboard.spec.ts, packages/gridstack/src/components/WidgetHeadline/WidgetHeadline.spec.js, packages/storybook-host/.storybook/main.scss
Add a new base input component to get rid of the vee validate rules
=> feat(BaseInputV3): Add new base input component

packages/core/src/components/inputs/BaseInputV3/BaseInputV3.vue, packages/core/src/components/inputs/SlugInput/SlugInput.spec.ts, packages/core/src/components/inputs/SlugInput/SlugInput.stories.ts, packages/core/src/components/inputs/SlugInput/SlugInput.vue, packages/core/src/components/inputs/index.ts
Adding new component SlugInput
=> feat: Introduce SlugInput

packages/core/src/components/inputs/SelectInput/SelectInput.vue
Removed the changeable width variable. Added again
=> fix(SelectInput): add changeable width

packages/core/src/components/inputs/NumberInputValidated/NumberInputValidated.spec.ts, packages/core/src/components/inputs/NumberInputValidated/NumberInputValidated.vue
vee validate model sync seem not sufficient to be found by test
=> fix(NumberInputValidated): expose modelValue via props

packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.spec.ts, packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.stories.ts, packages/core/src/components/cards/EditableEntityCard/EditableEntityCard.vue
Add `readOnly` prop to EditableEntityCard with default value `false`
=> Feat: EditableEntityCard with optional readOnly prop with default value false

packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.vue, packages/core/src/components/inputs/IbanInputValidated/IbanInputValidated.vue
Add computed property in baseinputvalidated to dynamically recheck validation.
Modified ibaninputvalidated so that can cominbed internal and passed rules.
=> Update ibanvalidation and baseinputvalited to allow combining of multiple validaiton rules

packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.vue, packages/core/src/components/inputs/IbanInputValidated/IbanInputValidated.vue
Reverts lion5/component-library#332
=> Revert "Update ibanvalidation and baseinputvalited to allow combining of multiple validaiton rules"

packages/core/src/components/inputs/BaseInputV3Validated/BaseInputV3Validated.vue, packages/core/src/components/inputs/IbanInputValidated/IbanInputValidated.vue
Reverts lion5/component-library#337
=> Revert "Revert "Update ibanvalidation and baseinputvalited to allow combining of multiple validaiton rules""

packages/core/src/components/boxes/ErrorBox/ErrorBox.spec.js, packages/core/src/components/boxes/ErrorBox/ErrorBox.stories.ts, packages/core/src/components/boxes/ErrorBox/ErrorBox.vue
- Add slot to be able to define custom errorbox content
- Add ability to hide error icon
=> Feat: Error box slot

package-lock.json, packages/core/src/components/buttons/BaseButton/BaseButton.stories.ts, packages/core/src/components/buttons/BaseButton/BaseButton.vue, packages/core/src/components/buttons/Buttons.mdx, packages/core/src/components/buttons/IconButton/IconButton.stories.ts, packages/core/src/components/buttons/IconButton/IconButton.vue
- Add a option to display the label of an icon button
- Add color variants to icon button
- Improve busy style of icon buttons and base buttons
- Improve buttons docs
=> feat(Button): Add labeled IconButtons
